/*
  # Create partner_submissions table

  1. New Tables
    - `partner_submissions`
      - `id` (bigint, primary key)
      - `user_id` (uuid, foreign key to auth.users)
      - Business details: name, website, instagram, contact info, category, neighborhood
      - Perk details: title, description, redemption method/details, images, logo, flags
      - `status` (enum: pending_payment, completed_payment, abandoned, approved, rejected)
      - `stripe_order_id` (bigint, foreign key to stripe_orders)
      - `created_at`, `updated_at` (timestamps)

  2. Security
    - Enable RLS on `partner_submissions` table
    - Add policy for users to manage their own submissions

  3. Indexes
    - Index on user_id for faster user-specific queries
    - Index on status for filtering by submission status
*/

-- Create the enum type for submission status
DO $$ BEGIN
    CREATE TYPE public.submission_status AS ENUM (
        'pending_payment',
        'completed_payment',
        'abandoned',
        'approved',
        'rejected'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Create the partner_submissions table
CREATE TABLE IF NOT EXISTS public.partner_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    
    -- Business Details
    business_name TEXT NOT NULL,
    business_website TEXT,
    business_instagram TEXT,
    contact_name TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    business_category TEXT NOT NULL,
    business_neighborhood TEXT NOT NULL,

    -- Perk Details
    perk_title TEXT NOT NULL,
    perk_description TEXT NOT NULL,
    perk_redemption_method TEXT NOT NULL,
    perk_redemption_details TEXT NOT NULL,
    perk_images TEXT[], -- Array of image URLs
    perk_logo TEXT,     -- Logo URL
    perk_is_portuguese_owned BOOLEAN NOT NULL DEFAULT FALSE,
    perk_needs_nif BOOLEAN NOT NULL DEFAULT FALSE,

    -- Submission Status and Timestamps
    status public.submission_status NOT NULL DEFAULT 'pending_payment',
    stripe_order_id BIGINT REFERENCES public.stripe_orders(id), -- Link to successful payment
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.partner_submissions ENABLE ROW LEVEL SECURITY;

-- Create RLS Policy: Users can view and insert their own submissions
CREATE POLICY "Users can manage their own partner submissions"
ON public.partner_submissions
FOR ALL
USING (auth.uid() = user_id);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_partner_submissions_user_id ON public.partner_submissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_partner_submissions_status ON public.partner_submissions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_partner_submissions_created_at ON public.partner_submissions USING btree (created_at);