-- Seed regulatory_rules table with current hardcoded rules
INSERT INTO public.regulatory_rules (rule_category, rule_id, title, description, threshold_value, threshold_currency, source_name, source_url, penalty_info, deadline_info, last_verified_at)
VALUES
    (
        'vat',
        'vat_exemption_threshold',
        'VAT Exemption Threshold (Article 53)',
        'Maximum annual turnover to remain exempt from charging VAT.',
        15000,
        'EUR',
        'Autoridade Tributária (AT)',
        'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/iva53.aspx',
        'Late registration penalties + 10% fine on unreported transactions.',
        'Registration required before reaching €15,000 annual turnover.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'vat',
        'vat_immediate_loss_threshold',
        'VAT Immediate Loss Threshold (125%)',
        'Turnover threshold where VAT exemption is lost immediately instead of next year.',
        18750,
        'EUR',
        'Autoridade Tributária (AT)',
        'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/iva53.aspx',
        'Liable for all uncharged VAT retroactively + penalties + interest.',
        'Immediate registration required upon crossing threshold.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'income_tax',
        'expense_justification_percentage',
        'Expense Justification Requirement',
        'Percentage of gross income that must be justified with documented professional expenses under Simplified Regime (0.75 coefficient).',
        15,
        'PERCENT',
        'Autoridade Tributária (AT)',
        'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/Pages/irs31.aspx',
        'Difference added back to taxable income (20-30% tax increase).',
        'Expenses must be classified by February 25th of following year.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'income_tax',
        'organized_accounting_threshold',
        'Organized Accounting Threshold',
        'Annual income threshold where switching from Simplified to Organized Accounting is mandatory.',
        200000,
        'EUR',
        'Autoridade Tributária (AT)',
        'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/cirs_rep/index.aspx',
        'Mandatory regime change, professional accountant required.',
        'Before exceeding €200,000 annual income.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'activity',
        'activity_opening_deadline',
        'Activity Opening Deadline',
        'Requirement to open activity (abertura de atividade) before starting commercial work.',
        0,
        'DAYS',
        'Portal das Finanças',
        'https://www.portaldasfinancas.gov.pt/',
        'Fines start at €500 for undeclared economic activity.',
        'Before issuing your first invoice.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'nif',
        'nif_registration_deadline',
        'NIF Registration Deadline (Residents)',
        'Deadline for registering for a NIF after becoming a tax resident.',
        60,
        'DAYS',
        'Autoridade Tributária (AT)',
        'https://www.portaldasfinancas.gov.pt/',
        'Penalties start at €375, residence renewal may be blocked.',
        'Within 60 days of arrival or becoming resident.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'niss',
        'niss_registration_deadline',
        'NISS Registration Deadline',
        'Deadline for social security registration after opening activity.',
        30,
        'DAYS',
        'Segurança Social',
        'https://www.seg-social.pt/',
        'AIMA can reject residence renewal. Automatic interest on late payments.',
        '30 days from first invoice or activity opening.',
        '2026-02-14T00:00:00Z'
    ),
    (
        'vat',
        'quarterly_vat_return_deadline',
        'Quarterly VAT Return Deadline',
        'Deadline for filing quarterly turnover returns (including exempt freelancers).',
        0,
        'DAYS',
        'Portal das Finanças',
        'https://www.portaldasfinancas.gov.pt/',
        'Mandatory reporting requirement, late filing penalties.',
        'End of month following each quarter (Jan 31, Apr 30, Jul 31, Oct 31).',
        '2026-02-14T00:00:00Z'
    )
ON CONFLICT (rule_id) DO UPDATE SET
    rule_category = EXCLUDED.rule_category,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    threshold_value = EXCLUDED.threshold_value,
    threshold_currency = EXCLUDED.threshold_currency,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    penalty_info = EXCLUDED.penalty_info,
    deadline_info = EXCLUDED.deadline_info,
    last_verified_at = EXCLUDED.last_verified_at,
    updated_at = now();
